site_name: "My Python Knowledge"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Project Setup: project_setup.md
  - Software Requirements: software_requirements.md
  - Chapters:
    - Functional Programming: chapters/functional_programming.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - toc.integrate
    - navigation.top
    - content.code.copy
  palette:
    primary: blue
    accent: blue
    toggle:
      icon: menu
      name: Menu
plugins:
 - search
 - mkdocstrings